### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by vilav** [postlight/liftoff#14]
Hello

New to the workflow, is there a way to set password protection per site / per post?

Thanks

**Comment by fdsimms** [comment]
Hi @vilav, so sorry about the delay in responding—password protection would depend on how you're hosting your site, since all this tool does is generate static html pages. [Netlify](https://www.netlify.com/) has a password-protected option on its paid plans, for example. I haven't used it before, but creating [an .htaccess file](url) also seems like one way to go.
